//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.14 at 10:59:51 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://apis_pack.soapapplicationdemo_1.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soapapplicationdemo_1.apis_pack;
